@startuml database_entities

entity game {
    gameId : GUID
    name
}

entity guild {
    guildId : GUID
    name : string
}

entity player {
    playerId: GUID
    name : string
}

entity character {
    characterId : GUID
    name : string
    role : string
    --
    characterClassId : GUID <<FK>>
}

entity item {
    itemId : GUID
    name :string
}

entity itemCharacteristic {
    itemCharacteristicId : GUID
}

entity abilityScore {
    abilityScoreId : GUID
}

entity raid {
    raidId : GUID
    name : string
}

entity characterClass {
    characterClassId : GUID
    Name : string
    Game : string
}

entity raidMeeting {
    raidMeetingId
    raidId : GUID
    startDate : datatime
    endDate : datatime
}


player ||--o{ character
character ||--|| abilityScore
character ||--|| characterClass
guild ||--o{ character
raidMeeting }o--|| guild
raidMeeting }o--|| raid


@enduml